/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Casino;

/**
 * The user can select the Member's preferred gaming device.
 * 
 * The Member name, Casino, and Member Level are prefilled from the Menu page.
 */
public class GamingDevice extends javax.swing.JFrame {

    /**
     */
    public GamingDevice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Roulette = new javax.swing.JCheckBox();
        BlackJack = new javax.swing.JCheckBox();
        Poker = new javax.swing.JCheckBox();
        Slots = new javax.swing.JCheckBox();
        MemberFirstNamePrefill1 = new javax.swing.JTextField();
        MemberLastNamePrefill1 = new javax.swing.JTextField();
        CasinoPrefill1 = new javax.swing.JTextField();
        MemberLevelPrefill = new javax.swing.JTextField();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("GamingDevice"); // NOI18N
        setPreferredSize(new java.awt.Dimension(395, 420));
        setResizable(false);
        getContentPane().setLayout(null);

        Roulette.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Roulette.setText("Roulette");
        Roulette.setOpaque(false);
        getContentPane().add(Roulette);
        Roulette.setBounds(70, 70, 100, 23);

        BlackJack.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BlackJack.setText("Black Jack");
        BlackJack.setOpaque(false);
        getContentPane().add(BlackJack);
        BlackJack.setBounds(70, 90, 100, 23);

        Poker.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Poker.setText("Poker");
        Poker.setOpaque(false);
        getContentPane().add(Poker);
        Poker.setBounds(70, 110, 100, 23);

        Slots.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Slots.setText("Slots");
        Slots.setOpaque(false);
        getContentPane().add(Slots);
        Slots.setBounds(70, 130, 100, 23);

        MemberFirstNamePrefill1.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        MemberFirstNamePrefill1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        MemberFirstNamePrefill1.setText("First");
        MemberFirstNamePrefill1.setBorder(null);
        MemberFirstNamePrefill1.setOpaque(false);
        MemberFirstNamePrefill1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemberFirstNamePrefill1ActionPerformed(evt);
            }
        });
        getContentPane().add(MemberFirstNamePrefill1);
        MemberFirstNamePrefill1.setBounds(230, 10, 60, 15);

        MemberLastNamePrefill1.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        MemberLastNamePrefill1.setText(" Last Prefill");
        MemberLastNamePrefill1.setBorder(null);
        MemberLastNamePrefill1.setOpaque(false);
        MemberLastNamePrefill1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemberLastNamePrefill1ActionPerformed(evt);
            }
        });
        getContentPane().add(MemberLastNamePrefill1);
        MemberLastNamePrefill1.setBounds(290, 10, 90, 15);

        CasinoPrefill1.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        CasinoPrefill1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CasinoPrefill1.setText("Casino Prefill");
        CasinoPrefill1.setBorder(null);
        CasinoPrefill1.setOpaque(false);
        CasinoPrefill1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CasinoPrefill1ActionPerformed(evt);
            }
        });
        getContentPane().add(CasinoPrefill1);
        CasinoPrefill1.setBounds(240, 30, 130, 15);

        MemberLevelPrefill.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        MemberLevelPrefill.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MemberLevelPrefill.setText("Member Level Prefill");
        MemberLevelPrefill.setBorder(null);
        MemberLevelPrefill.setOpaque(false);
        MemberLevelPrefill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemberLevelPrefillActionPerformed(evt);
            }
        });
        getContentPane().add(MemberLevelPrefill);
        MemberLevelPrefill.setBounds(240, 50, 130, 15);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Casino/gambling-dice.jpg"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 390, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MemberFirstNamePrefill1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MemberFirstNamePrefill1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MemberFirstNamePrefill1ActionPerformed

    private void MemberLastNamePrefill1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MemberLastNamePrefill1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MemberLastNamePrefill1ActionPerformed

    private void CasinoPrefill1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CasinoPrefill1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CasinoPrefill1ActionPerformed

    private void MemberLevelPrefillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MemberLevelPrefillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MemberLevelPrefillActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GamingDevice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GamingDevice().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JCheckBox BlackJack;
    private javax.swing.JTextField CasinoPrefill1;
    private javax.swing.JTextField MemberFirstNamePrefill1;
    private javax.swing.JTextField MemberLastNamePrefill1;
    private javax.swing.JTextField MemberLevelPrefill;
    private javax.swing.JCheckBox Poker;
    private javax.swing.JCheckBox Roulette;
    private javax.swing.JCheckBox Slots;
    // End of variables declaration//GEN-END:variables
}
