/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Casino;

/**
 * The user can select the Member's preferred gaming device.
 * 
 * The Member name, Casino, and Member Level are prefilled from the Menu page.
 */
public class GamingDevice extends javax.swing.JFrame {

    /**
     */
    public GamingDevice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Roulette = new javax.swing.JCheckBox();
        PokerLowStakes = new javax.swing.JCheckBox();
        PokerMediumStakes = new javax.swing.JCheckBox();
        PokerHighStakes = new javax.swing.JCheckBox();
        OneDollarSlot = new javax.swing.JCheckBox();
        QuarterSlot = new javax.swing.JCheckBox();
        FortuneWheel = new javax.swing.JCheckBox();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("GamingDevice"); // NOI18N
        setPreferredSize(new java.awt.Dimension(395, 420));
        setResizable(false);
        getContentPane().setLayout(null);

        Roulette.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Roulette.setText("Roulette");
        Roulette.setOpaque(false);
        getContentPane().add(Roulette);
        Roulette.setBounds(10, 30, 220, 25);

        PokerLowStakes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PokerLowStakes.setText("Poker Low Stakes");
        PokerLowStakes.setOpaque(false);
        getContentPane().add(PokerLowStakes);
        PokerLowStakes.setBounds(30, 40, 180, 40);

        PokerMediumStakes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PokerMediumStakes.setText("Poker Medium Stakes");
        PokerMediumStakes.setOpaque(false);
        getContentPane().add(PokerMediumStakes);
        PokerMediumStakes.setBounds(50, 70, 180, 25);

        PokerHighStakes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PokerHighStakes.setText("Poker High Stakes");
        PokerHighStakes.setOpaque(false);
        getContentPane().add(PokerHighStakes);
        PokerHighStakes.setBounds(70, 90, 150, 25);

        OneDollarSlot.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        OneDollarSlot.setText("One Dollar Slot");
        OneDollarSlot.setOpaque(false);
        OneDollarSlot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OneDollarSlotActionPerformed(evt);
            }
        });
        getContentPane().add(OneDollarSlot);
        OneDollarSlot.setBounds(90, 110, 290, 25);

        QuarterSlot.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        QuarterSlot.setText("Quarter Slot");
        QuarterSlot.setOpaque(false);
        getContentPane().add(QuarterSlot);
        QuarterSlot.setBounds(110, 130, 220, 25);

        FortuneWheel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FortuneWheel.setText("Wheel of Fortune");
        FortuneWheel.setOpaque(false);
        getContentPane().add(FortuneWheel);
        FortuneWheel.setBounds(130, 150, 220, 25);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Casino/gambling-dice.jpg"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 390, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OneDollarSlotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OneDollarSlotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OneDollarSlotActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GamingDevice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GamingDevice().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JCheckBox FortuneWheel;
    private javax.swing.JCheckBox OneDollarSlot;
    private javax.swing.JCheckBox PokerHighStakes;
    private javax.swing.JCheckBox PokerLowStakes;
    private javax.swing.JCheckBox PokerMediumStakes;
    private javax.swing.JCheckBox QuarterSlot;
    private javax.swing.JCheckBox Roulette;
    // End of variables declaration//GEN-END:variables
}
