/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Casino;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author hillman
 */
public class MemberInfo extends javax.swing.JFrame {
    
    private Connector conn;
    private Vector casNames, casIDs;
    private int memID;
    
    //add a new member
    public MemberInfo(Connector con){
        conn = con;
        initComponents();
        
        casNames = new Vector();
        casIDs = new Vector();
        getCasinos();
        memID = -999;
    }
    
    //lookup existing member
    public MemberInfo(Connector con, int memberID){
        conn = con;
        memID = memberID;
        initComponents();
        
        casNames = new Vector();
        casIDs = new Vector();
        getCasinos();
        
        String query = "select FIRSTNAME, LASTNAME, ADDRESSLINE1, CITY, STATE, ZIPCODE, COUNTRY, PHONENUMBER, EMAILADDRESS "
                + "from member "
                + "where MEMBERID="+memID;
        ResultSet rs =null;
        String firstName = "";
        String lastName = "";
        String street = "";
        String city = "";
        String state = "";
        String zipCode = "";
        String country = "";
        String phone = "";
        String email = "";
        
        try {
            rs =conn.execQuery(query);
            rs.next();
            firstName = rs.getString(1);
            lastName = rs.getString(2);
            street = rs.getString(3);
            city = rs.getString(4);
            state = rs.getString(5);
            zipCode = rs.getString(6);
            country = rs.getString(7);
            phone = rs.getString(8);
            email = rs.getString(9);
            
        } catch (SQLException ex) {
            Logger.getLogger(MemberInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
        MemberiD.setText(""+memID);
        FirstNameField.setText(firstName);
        LastNameField.setText(lastName);
        PhoneField.setText(phone);
        EmailField.setText(email);
        StreetField.setText(street);
        CityField.setText(city);
        StateField.setText(state);
        ZipCodeField.setText(zipCode);
        CountryField.setText(country);
        
    }
    

    /**
     * Creates new form MemberInfo
     */
    public MemberInfo() {
        initComponents();
    }
    
    
    private void getCasinos(){
        String query = "select CASINOID, CASINONAME " +
                "from CASINODETAILS ";
        try {
            ResultSet rs = conn.execQuery(query);
            
            while(rs.next()){
                casNames.add(rs.getString(2));
                casIDs.add(rs.getInt(1));
            }
            
            CasinoName.setListData(casNames);
            
        } catch (SQLException ex) {
            System.err.println(ex.getMessage());
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MemberIDLabel = new javax.swing.JTextField();
        MemberiD = new javax.swing.JTextField();
        FirstNameLabel = new javax.swing.JTextField();
        FirstNameField = new javax.swing.JTextField();
        LastNameLabel = new javax.swing.JTextField();
        LastNameField = new javax.swing.JTextField();
        PhoneLabel = new javax.swing.JTextField();
        PhoneField = new javax.swing.JTextField();
        EmailLabel = new javax.swing.JTextField();
        EmailField = new javax.swing.JTextField();
        StreetLabel = new javax.swing.JTextField();
        StreetField = new javax.swing.JTextField();
        CityLabel = new javax.swing.JTextField();
        CityField = new javax.swing.JTextField();
        StateLabel = new javax.swing.JTextField();
        StateField = new javax.swing.JTextField();
        ZipCodeLabel = new javax.swing.JTextField();
        ZipCodeField = new javax.swing.JTextField();
        CountryField = new javax.swing.JTextField();
        CountryLabel = new javax.swing.JTextField();
        MemberIDButton = new javax.swing.JButton();
        CasinoLabel = new javax.swing.JLabel();
        CasinoScrollPanel = new javax.swing.JScrollPane();
        CasinoName = new javax.swing.JList();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(425, 475));
        getContentPane().setLayout(null);

        MemberIDLabel.setEditable(false);
        MemberIDLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        MemberIDLabel.setForeground(new java.awt.Color(255, 255, 255));
        MemberIDLabel.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        MemberIDLabel.setText("Member ID");
        MemberIDLabel.setBorder(null);
        MemberIDLabel.setOpaque(false);
        MemberIDLabel.setPreferredSize(new java.awt.Dimension(61, 215));
        getContentPane().add(MemberIDLabel);
        MemberIDLabel.setBounds(130, 10, 70, 20);

        MemberiD.setEditable(false);
        MemberiD.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        MemberiD.setForeground(new java.awt.Color(153, 153, 153));
        MemberiD.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        MemberiD.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        MemberiD.setOpaque(false);
        getContentPane().add(MemberiD);
        MemberiD.setBounds(200, 10, 120, 20);

        FirstNameLabel.setEditable(false);
        FirstNameLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        FirstNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        FirstNameLabel.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        FirstNameLabel.setText("First Name");
        FirstNameLabel.setBorder(null);
        FirstNameLabel.setOpaque(false);
        FirstNameLabel.setPreferredSize(new java.awt.Dimension(61, 215));
        getContentPane().add(FirstNameLabel);
        FirstNameLabel.setBounds(130, 30, 70, 20);

        FirstNameField.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        FirstNameField.setForeground(new java.awt.Color(153, 153, 153));
        FirstNameField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        FirstNameField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        FirstNameField.setOpaque(false);
        getContentPane().add(FirstNameField);
        FirstNameField.setBounds(200, 30, 120, 20);

        LastNameLabel.setEditable(false);
        LastNameLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        LastNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        LastNameLabel.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        LastNameLabel.setText("Last Name");
        LastNameLabel.setBorder(null);
        LastNameLabel.setOpaque(false);
        LastNameLabel.setPreferredSize(new java.awt.Dimension(120, 20));
        getContentPane().add(LastNameLabel);
        LastNameLabel.setBounds(130, 50, 70, 20);

        LastNameField.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        LastNameField.setForeground(new java.awt.Color(153, 153, 153));
        LastNameField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        LastNameField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LastNameField.setOpaque(false);
        getContentPane().add(LastNameField);
        LastNameField.setBounds(200, 50, 120, 20);

        PhoneLabel.setEditable(false);
        PhoneLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        PhoneLabel.setForeground(new java.awt.Color(255, 255, 255));
        PhoneLabel.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        PhoneLabel.setText("Phone ");
        PhoneLabel.setBorder(null);
        PhoneLabel.setOpaque(false);
        getContentPane().add(PhoneLabel);
        PhoneLabel.setBounds(140, 70, 60, 20);

        PhoneField.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        PhoneField.setForeground(new java.awt.Color(153, 153, 153));
        PhoneField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        PhoneField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PhoneField.setOpaque(false);
        getContentPane().add(PhoneField);
        PhoneField.setBounds(200, 70, 120, 20);

        EmailLabel.setEditable(false);
        EmailLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        EmailLabel.setForeground(new java.awt.Color(255, 255, 255));
        EmailLabel.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        EmailLabel.setText("Email ");
        EmailLabel.setBorder(null);
        EmailLabel.setOpaque(false);
        getContentPane().add(EmailLabel);
        EmailLabel.setBounds(150, 90, 50, 15);

        EmailField.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        EmailField.setForeground(new java.awt.Color(153, 153, 153));
        EmailField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        EmailField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        EmailField.setOpaque(false);
        getContentPane().add(EmailField);
        EmailField.setBounds(200, 90, 120, 20);

        StreetLabel.setEditable(false);
        StreetLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        StreetLabel.setForeground(new java.awt.Color(255, 255, 255));
        StreetLabel.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        StreetLabel.setText("Street");
        StreetLabel.setBorder(null);
        StreetLabel.setOpaque(false);
        StreetLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StreetLabelActionPerformed(evt);
            }
        });
        getContentPane().add(StreetLabel);
        StreetLabel.setBounds(150, 110, 50, 20);

        StreetField.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        StreetField.setForeground(new java.awt.Color(153, 153, 153));
        StreetField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        StreetField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        StreetField.setOpaque(false);
        getContentPane().add(StreetField);
        StreetField.setBounds(200, 110, 120, 20);

        CityLabel.setEditable(false);
        CityLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        CityLabel.setForeground(new java.awt.Color(255, 255, 255));
        CityLabel.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        CityLabel.setText("City");
        CityLabel.setBorder(null);
        CityLabel.setOpaque(false);
        CityLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CityLabelActionPerformed(evt);
            }
        });
        getContentPane().add(CityLabel);
        CityLabel.setBounds(160, 130, 40, 15);

        CityField.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        CityField.setForeground(new java.awt.Color(153, 153, 153));
        CityField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        CityField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        CityField.setOpaque(false);
        getContentPane().add(CityField);
        CityField.setBounds(200, 130, 120, 20);

        StateLabel.setEditable(false);
        StateLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        StateLabel.setForeground(new java.awt.Color(255, 255, 255));
        StateLabel.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        StateLabel.setText("State");
        StateLabel.setBorder(null);
        StateLabel.setOpaque(false);
        StateLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StateLabelActionPerformed(evt);
            }
        });
        getContentPane().add(StateLabel);
        StateLabel.setBounds(150, 150, 50, 20);

        StateField.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        StateField.setForeground(new java.awt.Color(153, 153, 153));
        StateField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        StateField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        StateField.setOpaque(false);
        getContentPane().add(StateField);
        StateField.setBounds(200, 150, 120, 20);

        ZipCodeLabel.setEditable(false);
        ZipCodeLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        ZipCodeLabel.setForeground(new java.awt.Color(255, 255, 255));
        ZipCodeLabel.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ZipCodeLabel.setText("Zip Code");
        ZipCodeLabel.setBorder(null);
        ZipCodeLabel.setOpaque(false);
        getContentPane().add(ZipCodeLabel);
        ZipCodeLabel.setBounds(140, 170, 60, 20);

        ZipCodeField.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        ZipCodeField.setForeground(new java.awt.Color(153, 153, 153));
        ZipCodeField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        ZipCodeField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ZipCodeField.setOpaque(false);
        getContentPane().add(ZipCodeField);
        ZipCodeField.setBounds(200, 170, 120, 20);

        CountryField.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        CountryField.setForeground(new java.awt.Color(153, 153, 153));
        CountryField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        CountryField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        CountryField.setOpaque(false);
        getContentPane().add(CountryField);
        CountryField.setBounds(200, 190, 120, 20);

        CountryLabel.setEditable(false);
        CountryLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        CountryLabel.setForeground(new java.awt.Color(255, 255, 255));
        CountryLabel.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        CountryLabel.setText("Country");
        CountryLabel.setBorder(null);
        CountryLabel.setOpaque(false);
        getContentPane().add(CountryLabel);
        CountryLabel.setBounds(140, 190, 60, 20);

        MemberIDButton.setBackground(new java.awt.Color(0, 0, 0));
        MemberIDButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MemberIDButton.setText("Get New Membership");
        MemberIDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemberIDButtonActionPerformed(evt);
            }
        });
        getContentPane().add(MemberIDButton);
        MemberIDButton.setBounds(210, 330, 170, 23);

        CasinoLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CasinoLabel.setForeground(new java.awt.Color(255, 255, 255));
        CasinoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        CasinoLabel.setText("Casino");
        getContentPane().add(CasinoLabel);
        CasinoLabel.setBounds(190, 240, 70, 20);

        CasinoScrollPanel.setBackground(new java.awt.Color(0, 51, 0));
        CasinoScrollPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CasinoScrollPanel.setForeground(new java.awt.Color(255, 255, 255));
        CasinoScrollPanel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        CasinoName.setBackground(new java.awt.Color(0, 0, 0));
        CasinoName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CasinoName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CasinoName.setForeground(new java.awt.Color(255, 255, 255));
        CasinoName.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Orbit", "Rost Petals", "Horse Shoe", "Oasis", "Forum" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        CasinoName.setOpaque(false);
        CasinoName.setSelectionBackground(new java.awt.Color(0, 0, 0));
        CasinoName.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                CasinoNameValueChanged(evt);
            }
        });
        CasinoScrollPanel.setViewportView(CasinoName);

        getContentPane().add(CasinoScrollPanel);
        CasinoScrollPanel.setBounds(270, 240, 100, 80);

        Background.setForeground(new java.awt.Color(204, 204, 204));
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Casino/cards black edited.jpg"))); // NOI18N
        Background.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(Background);
        Background.setBounds(0, -20, 410, 452);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StreetLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StreetLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StreetLabelActionPerformed

    private void CityLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CityLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CityLabelActionPerformed

    private void StateLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StateLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StateLabelActionPerformed

    private void CasinoNameValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_CasinoNameValueChanged
        // Set the casinoID and fill in the stuff at the bottom.
    }//GEN-LAST:event_CasinoNameValueChanged

    private void MemberIDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MemberIDButtonActionPerformed
        // TODO add your handling code here:
        String firstName = "'"+FirstNameField.getText()+"', ";
        String lastName = "'"+LastNameField.getText()+"', ";
        String phone = "'"+PhoneField.getText()+"', ";
        String email = "'"+EmailField.getText()+"' ";
        String street = "'"+StreetField.getText()+"', ";
        String city = "'"+CityField.getText()+"', ";
        String state = "'"+StateField.getText()+"', ";
        String zipCode = "'"+ZipCodeField.getText()+"', ";
        String country = "'"+CountryField.getText()+"', ";
        
        int casinoID = (int)(casIDs.get(CasinoName.getSelectedIndex()));
        String insert1;
        if(memID == -999){
            insert1 = "insert into MEMBER (FIRSTNAME, LASTNAME, ADDRESSLINE1, CITY, STATE, ZIPCODE, COUNTRY, PHONENUMBER, EMAILADDRESS) values ("
                    + firstName+lastName+street+city+state+zipCode+country+phone+email+")";
        
            try {
                conn.execUpdate(insert1);
                ResultSet newId = conn.execQuery("select max(MEMBERID) from MEMBER");
                newId.next();
                memID = newId.getInt(1);
            } catch (SQLException ex) {
                System.err.println(ex);
            }
        }
        
        String insert2 = "insert into CASINOMEMBERSHIP (MEMBERID, CASINOID, MEMBERSHIPTYPE) values ("
                + memID+", "+casinoID+", 'Bronze'"+")";
        try {
            conn.execUpdate(insert2);
        } catch (SQLException ex) {
            System.err.println(ex);
        }
        MemberiD.setText(""+memID);
    }//GEN-LAST:event_MemberIDButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemberInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemberInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemberInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemberInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemberInfo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel CasinoLabel;
    private javax.swing.JList CasinoName;
    private javax.swing.JScrollPane CasinoScrollPanel;
    private javax.swing.JTextField CityField;
    private javax.swing.JTextField CityLabel;
    private javax.swing.JTextField CountryField;
    private javax.swing.JTextField CountryLabel;
    private javax.swing.JTextField EmailField;
    private javax.swing.JTextField EmailLabel;
    private javax.swing.JTextField FirstNameField;
    private javax.swing.JTextField FirstNameLabel;
    private javax.swing.JTextField LastNameField;
    private javax.swing.JTextField LastNameLabel;
    private javax.swing.JButton MemberIDButton;
    private javax.swing.JTextField MemberIDLabel;
    private javax.swing.JTextField MemberiD;
    private javax.swing.JTextField PhoneField;
    private javax.swing.JTextField PhoneLabel;
    private javax.swing.JTextField StateField;
    private javax.swing.JTextField StateLabel;
    private javax.swing.JTextField StreetField;
    private javax.swing.JTextField StreetLabel;
    private javax.swing.JTextField ZipCodeField;
    private javax.swing.JTextField ZipCodeLabel;
    // End of variables declaration//GEN-END:variables
}
