
package Casino;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.WindowConstants;

/**
 *First page of the casino user interface.
 * If the client is a new member, the user checks the box labeled New Member 
 * and is automatically redirected to the Member Info form.
 * 
 * If the client is an existing member, the user enters the Member ID and the 
 * destination casino.  Once this is entered, the Name, Casino, and Member Level 
 * automatically fill on the remaining pages in the interface. 
 * 
 * Once the casino is selected from the drop down box, the selected casino 
 * address is automatically filled in.  
 * 
 * The user can select from the menu bar at the top of the page to be 
 * redirected to the linked pages.
 * 
 */
public class MenuPage extends javax.swing.JFrame {
    
    private Connector conn;
    private int casinoID = 1;//accepts the value of the selected casino
    private String casinoName = "haha";
    private int memberID =1001;//accepts the value of the selected member
    private ResultSet rs;
    
    public MenuPage(Connector con){
        conn = con;
        initComponents();
    }

    /**
     */
    public MenuPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MemberNameLabel = new javax.swing.JLabel();
        IDField = new javax.swing.JTextField();
        MemberLevelLabel = new javax.swing.JLabel();
        MemberLevel = new javax.swing.JTextField();
        CasinoLabel = new javax.swing.JLabel();
        CasinoScrollPanel = new javax.swing.JScrollPane();
        CasinoName = new javax.swing.JList();
        AddressLine1Prefill = new javax.swing.JTextField();
        AddressLine2Prefill = new javax.swing.JTextField();
        CityPrefill = new javax.swing.JTextField();
        StatePrefill = new javax.swing.JTextField();
        ZipPrefill = new javax.swing.JTextField();
        PhoneNumberPrefill = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Background = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        Member = new javax.swing.JMenu();
        Rooms = new javax.swing.JMenu();
        Restaurant = new javax.swing.JMenu();
        Device = new javax.swing.JMenu();
        Spa = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("MenuPage"); // NOI18N
        setPreferredSize(new java.awt.Dimension(448, 310));
        getContentPane().setLayout(null);

        MemberNameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MemberNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        MemberNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        MemberNameLabel.setText("Member ID");
        getContentPane().add(MemberNameLabel);
        MemberNameLabel.setBounds(0, 30, 90, 20);

        IDField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        IDField.setForeground(new java.awt.Color(255, 255, 255));
        IDField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        IDField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        IDField.setOpaque(false);
        IDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDFieldActionPerformed(evt);
            }
        });
        getContentPane().add(IDField);
        IDField.setBounds(100, 30, 100, 19);

        MemberLevelLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MemberLevelLabel.setForeground(new java.awt.Color(255, 255, 255));
        MemberLevelLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        MemberLevelLabel.setText("Member Level");
        getContentPane().add(MemberLevelLabel);
        MemberLevelLabel.setBounds(0, 50, 90, 20);

        MemberLevel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MemberLevel.setForeground(new java.awt.Color(255, 255, 255));
        MemberLevel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MemberLevel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MemberLevel.setOpaque(false);
        getContentPane().add(MemberLevel);
        MemberLevel.setBounds(100, 50, 100, 19);

        CasinoLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CasinoLabel.setForeground(new java.awt.Color(255, 255, 255));
        CasinoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        CasinoLabel.setText("Casino");
        getContentPane().add(CasinoLabel);
        CasinoLabel.setBounds(20, 70, 70, 20);

        CasinoScrollPanel.setBackground(new java.awt.Color(0, 51, 0));
        CasinoScrollPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CasinoScrollPanel.setForeground(new java.awt.Color(255, 255, 255));
        CasinoScrollPanel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        CasinoName.setBackground(new java.awt.Color(0, 51, 0));
        CasinoName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CasinoName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CasinoName.setForeground(new java.awt.Color(255, 255, 255));
        CasinoName.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Orbit", "Rost Petals", "Horse Shoe", "Oasis", "Forum" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        CasinoName.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                CasinoNameValueChanged(evt);
            }
        });
        CasinoScrollPanel.setViewportView(CasinoName);

        getContentPane().add(CasinoScrollPanel);
        CasinoScrollPanel.setBounds(100, 70, 100, 80);

        AddressLine1Prefill.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        AddressLine1Prefill.setForeground(new java.awt.Color(255, 255, 255));
        AddressLine1Prefill.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        AddressLine1Prefill.setText("Address Line 1 Prefill");
        AddressLine1Prefill.setBorder(null);
        AddressLine1Prefill.setOpaque(false);
        getContentPane().add(AddressLine1Prefill);
        AddressLine1Prefill.setBounds(10, 150, 180, 14);

        AddressLine2Prefill.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        AddressLine2Prefill.setForeground(new java.awt.Color(255, 255, 255));
        AddressLine2Prefill.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        AddressLine2Prefill.setText("Address Line 2 Prefill");
        AddressLine2Prefill.setBorder(null);
        AddressLine2Prefill.setOpaque(false);
        getContentPane().add(AddressLine2Prefill);
        AddressLine2Prefill.setBounds(10, 170, 180, 14);

        CityPrefill.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        CityPrefill.setForeground(new java.awt.Color(255, 255, 255));
        CityPrefill.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        CityPrefill.setText("City Prefill");
        CityPrefill.setBorder(null);
        CityPrefill.setOpaque(false);
        getContentPane().add(CityPrefill);
        CityPrefill.setBounds(10, 190, 180, 14);

        StatePrefill.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        StatePrefill.setForeground(new java.awt.Color(255, 255, 255));
        StatePrefill.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        StatePrefill.setText("State Prefill");
        StatePrefill.setBorder(null);
        StatePrefill.setOpaque(false);
        getContentPane().add(StatePrefill);
        StatePrefill.setBounds(10, 210, 60, 14);

        ZipPrefill.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        ZipPrefill.setForeground(new java.awt.Color(255, 255, 255));
        ZipPrefill.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        ZipPrefill.setText("Zip Prefill");
        ZipPrefill.setBorder(null);
        ZipPrefill.setOpaque(false);
        getContentPane().add(ZipPrefill);
        ZipPrefill.setBounds(80, 210, 50, 14);

        PhoneNumberPrefill.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        PhoneNumberPrefill.setForeground(new java.awt.Color(255, 255, 255));
        PhoneNumberPrefill.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        PhoneNumberPrefill.setText("Phone Number Prefill");
        PhoneNumberPrefill.setBorder(null);
        PhoneNumberPrefill.setOpaque(false);
        getContentPane().add(PhoneNumberPrefill);
        PhoneNumberPrefill.setBounds(10, 230, 180, 14);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("New Member");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(100, 10, 160, 20);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Casino/MenuPic.jpg"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 448, 251);

        Member.setText("Member");
        Member.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MemberMouseClicked(evt);
            }
        });
        Menu.add(Member);

        Rooms.setText("Rooms");
        Rooms.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RoomsMouseClicked(evt);
            }
        });
        Menu.add(Rooms);

        Restaurant.setText("Restaurant");
        Restaurant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RestaurantMouseClicked(evt);
            }
        });
        Menu.add(Restaurant);

        Device.setText("Gaming Device");
        Device.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeviceMouseClicked(evt);
            }
        });
        Menu.add(Device);

        Spa.setText("Spa");
        Spa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SpaMouseClicked(evt);
            }
        });
        Menu.add(Spa);

        setJMenuBar(Menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CasinoNameValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_CasinoNameValueChanged
        // Set the casinoID and fill in the stuff at the bottom.
        int rsIndex = CasinoName.getSelectedIndex()+1;
        try {
            rs.absolute(rsIndex);
            casinoID = rs.getInt("CASINOID");
            casinoName = rs.getString("CASINONAME");
            AddressLine1Prefill.setText(rs.getString("ADDRESSLINE1"));
            AddressLine2Prefill.setText(rs.getString("ADDRESSLINE2"));
            CityPrefill.setText(rs.getString("CITY"));
            StatePrefill.setText(rs.getString("STATE"));
            ZipPrefill.setText(rs.getString("ZIPCODE"));
            PhoneNumberPrefill.setText(rs.getString("PHONENUMBER"));
            MemberLevel.setText(rs.getString("MEMBERSHIPTYPE"));
        } catch (SQLException ex) {
            Logger.getLogger(MenuPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CasinoNameValueChanged

    private void MemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MemberMouseClicked
        // TODO add your handling code here:
        try{
            memberID = Integer.parseInt(IDField.getText());
        }
        catch(java.lang.NumberFormatException nfe){
            
        }
        MemberInfo mif = new MemberInfo(conn, memberID);
        mif.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        mif.setVisible(true);
    }//GEN-LAST:event_MemberMouseClicked

    private void RoomsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoomsMouseClicked
        // TODO add your handling code here:
        Rooms rf = new Rooms(conn, casinoID, casinoName);
        rf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        rf.setVisible(true);
    }//GEN-LAST:event_RoomsMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MemberInfo mif = new MemberInfo(conn);
        mif.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        mif.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void RestaurantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RestaurantMouseClicked
        // TODO add your handling code here:
        Restaurant rsf =new Restaurant(conn, casinoID);
        rsf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        rsf.setVisible(true);
    }//GEN-LAST:event_RestaurantMouseClicked

    private void DeviceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeviceMouseClicked
        // TODO add your handling code here:
        GamingDevice rf = new GamingDevice(conn, casinoID);
        rf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        rf.setVisible(true);
    }//GEN-LAST:event_DeviceMouseClicked

    private void SpaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SpaMouseClicked
        // TODO add your handling code here:
        Spa rf = new Spa(conn, casinoID);
        rf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        rf.setVisible(true);
    }//GEN-LAST:event_SpaMouseClicked

    
    private void IDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDFieldActionPerformed
        // TODO add your handling code here:
        try{
            memberID = Integer.parseInt(IDField.getText());
            
        }
        catch(java.lang.NumberFormatException nfe){
            IDField.setText(""+memberID);
        }
        
        rs = null;
        String query = "select * " +
            "from CASINODETAILS as cd " +
            "join CASINOMEMBERSHIP as cm " +
            "	on cd.CASINOID = cm.CASINOID "
                + "where cm.MEMBERID ="+memberID;
        try {
            rs = conn.execQuery(query);
            Vector vec = new Vector();
            while(rs.next()){
                vec.add(rs.getString(2));
            }
            CasinoName.setListData(vec);
        } catch (SQLException ex) {
            Logger.getLogger(MenuPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_IDFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MenuPage().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressLine1Prefill;
    private javax.swing.JTextField AddressLine2Prefill;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel CasinoLabel;
    private javax.swing.JList CasinoName;
    private javax.swing.JScrollPane CasinoScrollPanel;
    private javax.swing.JTextField CityPrefill;
    private javax.swing.JMenu Device;
    private javax.swing.JTextField IDField;
    private javax.swing.JMenu Member;
    private javax.swing.JTextField MemberLevel;
    private javax.swing.JLabel MemberLevelLabel;
    private javax.swing.JLabel MemberNameLabel;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JTextField PhoneNumberPrefill;
    private javax.swing.JMenu Restaurant;
    private javax.swing.JMenu Rooms;
    private javax.swing.JMenu Spa;
    private javax.swing.JTextField StatePrefill;
    private javax.swing.JTextField ZipPrefill;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
