/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Casino;

/**
 * The user can check the selection of food for the member.  Several items
 * can be selected simultaneously. 
 * 
 * The Member name, Casino, and Member Level are prefilled from the Menu page.
 */
public class Restaurant extends javax.swing.JFrame {

    /**
     */
    public Restaurant() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BreakfastLabel = new javax.swing.JLabel();
        Continental = new javax.swing.JCheckBox();
        Cereal = new javax.swing.JCheckBox();
        Waffles = new javax.swing.JCheckBox();
        LunchLabel = new javax.swing.JLabel();
        Salad = new javax.swing.JCheckBox();
        Pasta = new javax.swing.JCheckBox();
        Burger = new javax.swing.JCheckBox();
        Dinner = new javax.swing.JLabel();
        American = new javax.swing.JCheckBox();
        Asian = new javax.swing.JCheckBox();
        Mediterranean = new javax.swing.JCheckBox();
        Drinks = new javax.swing.JLabel();
        Coffee = new javax.swing.JCheckBox();
        Soda = new javax.swing.JCheckBox();
        Wine = new javax.swing.JCheckBox();
        MemberFirstNamePrefill1 = new javax.swing.JTextField();
        MemberLastNamePrefill1 = new javax.swing.JTextField();
        CasinoPrefill = new javax.swing.JTextField();
        MemberLevelPrefill = new javax.swing.JTextField();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Restaurant"); // NOI18N
        setPreferredSize(new java.awt.Dimension(440, 330));
        setResizable(false);
        getContentPane().setLayout(null);

        BreakfastLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BreakfastLabel.setForeground(new java.awt.Color(255, 255, 255));
        BreakfastLabel.setText("Breakfast");
        getContentPane().add(BreakfastLabel);
        BreakfastLabel.setBounds(40, 10, 70, 30);

        Continental.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Continental.setForeground(new java.awt.Color(255, 255, 255));
        Continental.setText("Continental");
        Continental.setOpaque(false);
        getContentPane().add(Continental);
        Continental.setBounds(20, 30, 110, 23);

        Cereal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Cereal.setForeground(new java.awt.Color(255, 255, 255));
        Cereal.setText("Cereal");
        Cereal.setOpaque(false);
        getContentPane().add(Cereal);
        Cereal.setBounds(20, 50, 110, 23);

        Waffles.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Waffles.setForeground(new java.awt.Color(255, 255, 255));
        Waffles.setText("Waffles");
        Waffles.setOpaque(false);
        getContentPane().add(Waffles);
        Waffles.setBounds(20, 70, 110, 23);

        LunchLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LunchLabel.setForeground(new java.awt.Color(255, 255, 255));
        LunchLabel.setText("Lunch");
        getContentPane().add(LunchLabel);
        LunchLabel.setBounds(150, 60, 60, 30);

        Salad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Salad.setForeground(new java.awt.Color(255, 255, 255));
        Salad.setText("Salad");
        Salad.setOpaque(false);
        getContentPane().add(Salad);
        Salad.setBounds(130, 80, 110, 23);

        Pasta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Pasta.setForeground(new java.awt.Color(255, 255, 255));
        Pasta.setText("Pasta");
        Pasta.setOpaque(false);
        getContentPane().add(Pasta);
        Pasta.setBounds(130, 100, 110, 23);

        Burger.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Burger.setForeground(new java.awt.Color(255, 255, 255));
        Burger.setText("Burger");
        Burger.setOpaque(false);
        getContentPane().add(Burger);
        Burger.setBounds(130, 120, 110, 23);

        Dinner.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Dinner.setForeground(new java.awt.Color(255, 255, 255));
        Dinner.setText("Dinner");
        getContentPane().add(Dinner);
        Dinner.setBounds(60, 130, 60, 30);

        American.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        American.setForeground(new java.awt.Color(255, 255, 255));
        American.setText("American");
        American.setOpaque(false);
        getContentPane().add(American);
        American.setBounds(40, 150, 110, 23);

        Asian.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Asian.setForeground(new java.awt.Color(255, 255, 255));
        Asian.setText("Asian");
        Asian.setOpaque(false);
        getContentPane().add(Asian);
        Asian.setBounds(40, 170, 110, 23);

        Mediterranean.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Mediterranean.setForeground(new java.awt.Color(255, 255, 255));
        Mediterranean.setText("Mediterranean");
        Mediterranean.setOpaque(false);
        getContentPane().add(Mediterranean);
        Mediterranean.setBounds(40, 190, 110, 23);

        Drinks.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Drinks.setForeground(new java.awt.Color(255, 255, 255));
        Drinks.setText("Drinks");
        getContentPane().add(Drinks);
        Drinks.setBounds(170, 200, 60, 30);

        Coffee.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Coffee.setForeground(new java.awt.Color(255, 255, 255));
        Coffee.setText("Coffee");
        Coffee.setOpaque(false);
        getContentPane().add(Coffee);
        Coffee.setBounds(150, 220, 110, 23);

        Soda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Soda.setForeground(new java.awt.Color(255, 255, 255));
        Soda.setText("Soda");
        Soda.setOpaque(false);
        getContentPane().add(Soda);
        Soda.setBounds(150, 240, 110, 23);

        Wine.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Wine.setForeground(new java.awt.Color(255, 255, 255));
        Wine.setText("Wine");
        Wine.setOpaque(false);
        Wine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WineActionPerformed(evt);
            }
        });
        getContentPane().add(Wine);
        Wine.setBounds(150, 260, 110, 23);

        MemberFirstNamePrefill1.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        MemberFirstNamePrefill1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        MemberFirstNamePrefill1.setText("First");
        MemberFirstNamePrefill1.setBorder(null);
        MemberFirstNamePrefill1.setOpaque(false);
        MemberFirstNamePrefill1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemberFirstNamePrefill1ActionPerformed(evt);
            }
        });
        getContentPane().add(MemberFirstNamePrefill1);
        MemberFirstNamePrefill1.setBounds(210, 260, 60, 14);

        MemberLastNamePrefill1.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        MemberLastNamePrefill1.setText(" Last Prefill");
        MemberLastNamePrefill1.setBorder(null);
        MemberLastNamePrefill1.setOpaque(false);
        MemberLastNamePrefill1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemberLastNamePrefill1ActionPerformed(evt);
            }
        });
        getContentPane().add(MemberLastNamePrefill1);
        MemberLastNamePrefill1.setBounds(270, 260, 90, 14);

        CasinoPrefill.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        CasinoPrefill.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CasinoPrefill.setText("Casino Prefill");
        CasinoPrefill.setBorder(null);
        CasinoPrefill.setOpaque(false);
        CasinoPrefill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CasinoPrefillActionPerformed(evt);
            }
        });
        getContentPane().add(CasinoPrefill);
        CasinoPrefill.setBounds(210, 270, 130, 14);

        MemberLevelPrefill.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        MemberLevelPrefill.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MemberLevelPrefill.setText("Member Level Prefill");
        MemberLevelPrefill.setBorder(null);
        MemberLevelPrefill.setOpaque(false);
        MemberLevelPrefill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemberLevelPrefillActionPerformed(evt);
            }
        });
        getContentPane().add(MemberLevelPrefill);
        MemberLevelPrefill.setBounds(220, 280, 130, 20);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Casino/wine3Resized.jpg"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 440, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void WineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WineActionPerformed

    private void MemberFirstNamePrefill1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MemberFirstNamePrefill1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MemberFirstNamePrefill1ActionPerformed

    private void MemberLastNamePrefill1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MemberLastNamePrefill1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MemberLastNamePrefill1ActionPerformed

    private void MemberLevelPrefillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MemberLevelPrefillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MemberLevelPrefillActionPerformed

    private void CasinoPrefillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CasinoPrefillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CasinoPrefillActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restaurant().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox American;
    private javax.swing.JCheckBox Asian;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel BreakfastLabel;
    private javax.swing.JCheckBox Burger;
    private javax.swing.JTextField CasinoPrefill;
    private javax.swing.JCheckBox Cereal;
    private javax.swing.JCheckBox Coffee;
    private javax.swing.JCheckBox Continental;
    private javax.swing.JLabel Dinner;
    private javax.swing.JLabel Drinks;
    private javax.swing.JLabel LunchLabel;
    private javax.swing.JCheckBox Mediterranean;
    private javax.swing.JTextField MemberFirstNamePrefill1;
    private javax.swing.JTextField MemberLastNamePrefill1;
    private javax.swing.JTextField MemberLevelPrefill;
    private javax.swing.JCheckBox Pasta;
    private javax.swing.JCheckBox Salad;
    private javax.swing.JCheckBox Soda;
    private javax.swing.JCheckBox Waffles;
    private javax.swing.JCheckBox Wine;
    // End of variables declaration//GEN-END:variables
}
