/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Casino;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * The user can check the selection of food for the member.  Several items
 * can be selected simultaneously. 
 * 
 * The Member name, Casino, and Member Level are prefilled from the Menu page.
 */
public class Restaurant extends javax.swing.JFrame {
    
    Connector conn;
    int casID;
    public Restaurant(Connector con, int casinoID){
        conn = con;
        casID = casinoID;
        initComponents();
        
        String queryBase = "select FOODNAME, FOODTIMING, PRICE\n" +
            "from FOODMENU\n"
                + "where CASINOID="+casID+" and FOODCATEGORY = '";
        
        String queryAppetizer = queryBase + "APPETIZER'";
        String queryEntree = queryBase +"ENTREES'";
        String queryDeserts = queryBase+"DESERTS'";
        
        String appet ="";
        String entr = "";
        String desr ="";
        
        ResultSet rs1 = null;
        ResultSet rs2 = null;
        ResultSet rs3 = null;
        try {
            rs1 = conn.execQuery(queryAppetizer);
            while(rs1.next()){
                appet += rs1.getString(1)+" "+rs1.getString(2)+" "+rs1.getString(3)+"\n";
            }
        } catch (SQLException ex) {
            
        }
        try {
            rs2 = conn.execQuery(queryEntree);
            while(rs1.next()){
                entr += rs2.getString(1)+" "+rs2.getString(2)+" "+rs2.getString(3)+"\n";
            }
        } catch (SQLException ex) {
            
        }
        try {
            rs3 = conn.execQuery(queryDeserts);
            while(rs1.next()){
                desr += rs3.getString(1)+" "+rs3.getString(2)+" "+rs3.getString(3)+"\n";
            }
        } catch (SQLException ex) {
            
        }
        
        jTextArea1.setText(appet);
        jTextArea2.setText(entr);
        jTextArea3.setText(desr);
    }

    /**
     */
    public Restaurant() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BreakfastLabel = new javax.swing.JLabel();
        LunchLabel = new javax.swing.JLabel();
        Dinner = new javax.swing.JLabel();
        Appetizer = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        Entree = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Desert = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Restaurant"); // NOI18N
        setPreferredSize(new java.awt.Dimension(440, 330));
        setResizable(false);
        getContentPane().setLayout(null);

        BreakfastLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BreakfastLabel.setForeground(new java.awt.Color(255, 255, 255));
        BreakfastLabel.setText("Appetizer");
        getContentPane().add(BreakfastLabel);
        BreakfastLabel.setBounds(40, 10, 70, 30);

        LunchLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LunchLabel.setForeground(new java.awt.Color(255, 255, 255));
        LunchLabel.setText("Entree");
        getContentPane().add(LunchLabel);
        LunchLabel.setBounds(100, 100, 60, 30);

        Dinner.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Dinner.setForeground(new java.awt.Color(255, 255, 255));
        Dinner.setText("Desert");
        getContentPane().add(Dinner);
        Dinner.setBounds(150, 200, 60, 30);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.setOpaque(false);
        Appetizer.setViewportView(jTextArea3);

        getContentPane().add(Appetizer);
        Appetizer.setBounds(10, 40, 190, 60);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setOpaque(false);
        Entree.setViewportView(jTextArea1);

        getContentPane().add(Entree);
        Entree.setBounds(70, 130, 190, 60);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setOpaque(false);
        Desert.setViewportView(jTextArea2);

        getContentPane().add(Desert);
        Desert.setBounds(130, 230, 190, 60);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Casino/wine3Resized.jpg"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 440, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restaurant().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Appetizer;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel BreakfastLabel;
    private javax.swing.JScrollPane Desert;
    private javax.swing.JLabel Dinner;
    private javax.swing.JScrollPane Entree;
    private javax.swing.JLabel LunchLabel;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    // End of variables declaration//GEN-END:variables
}
