/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Casino;

/**
 * The user can check the selection of food for the member.  Several items
 * can be selected simultaneously. 
 * 
 * The Member name, Casino, and Member Level are prefilled from the Menu page.
 */
public class Restaurant extends javax.swing.JFrame {

    /**
     */
    public Restaurant() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BreakfastLabel = new javax.swing.JLabel();
        Continental = new javax.swing.JCheckBox();
        Cereal = new javax.swing.JCheckBox();
        Waffles = new javax.swing.JCheckBox();
        LunchLabel = new javax.swing.JLabel();
        Salad = new javax.swing.JCheckBox();
        Pasta = new javax.swing.JCheckBox();
        Burger = new javax.swing.JCheckBox();
        Dinner = new javax.swing.JLabel();
        American = new javax.swing.JCheckBox();
        Asian = new javax.swing.JCheckBox();
        Coffee = new javax.swing.JCheckBox();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Restaurant"); // NOI18N
        setPreferredSize(new java.awt.Dimension(440, 330));
        setResizable(false);
        getContentPane().setLayout(null);

        BreakfastLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BreakfastLabel.setForeground(new java.awt.Color(255, 255, 255));
        BreakfastLabel.setText("Appetizer");
        getContentPane().add(BreakfastLabel);
        BreakfastLabel.setBounds(40, 10, 70, 30);

        Continental.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Continental.setForeground(new java.awt.Color(255, 255, 255));
        Continental.setText("Tuscan Hummus");
        Continental.setOpaque(false);
        getContentPane().add(Continental);
        Continental.setBounds(20, 30, 160, 25);

        Cereal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Cereal.setForeground(new java.awt.Color(255, 255, 255));
        Cereal.setText("Spinach Artichoke Dip");
        Cereal.setOpaque(false);
        getContentPane().add(Cereal);
        Cereal.setBounds(20, 50, 160, 25);

        Waffles.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Waffles.setForeground(new java.awt.Color(255, 255, 255));
        Waffles.setText("Lettuce Wraps");
        Waffles.setOpaque(false);
        getContentPane().add(Waffles);
        Waffles.setBounds(20, 70, 110, 25);

        LunchLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LunchLabel.setForeground(new java.awt.Color(255, 255, 255));
        LunchLabel.setText("Entree");
        getContentPane().add(LunchLabel);
        LunchLabel.setBounds(100, 100, 60, 30);

        Salad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Salad.setForeground(new java.awt.Color(255, 255, 255));
        Salad.setText("Original BBQ Chicken");
        Salad.setOpaque(false);
        getContentPane().add(Salad);
        Salad.setBounds(80, 120, 160, 25);

        Pasta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Pasta.setForeground(new java.awt.Color(255, 255, 255));
        Pasta.setText("Spicy Chipotle Chicken");
        Pasta.setOpaque(false);
        getContentPane().add(Pasta);
        Pasta.setBounds(80, 140, 150, 25);

        Burger.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Burger.setForeground(new java.awt.Color(255, 255, 255));
        Burger.setText("Thai Chicken");
        Burger.setOpaque(false);
        getContentPane().add(Burger);
        Burger.setBounds(80, 160, 110, 25);

        Dinner.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Dinner.setForeground(new java.awt.Color(255, 255, 255));
        Dinner.setText("Desert");
        getContentPane().add(Dinner);
        Dinner.setBounds(150, 210, 60, 30);

        American.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        American.setForeground(new java.awt.Color(255, 255, 255));
        American.setText("Red Velvet Cake");
        American.setOpaque(false);
        getContentPane().add(American);
        American.setBounds(120, 230, 130, 25);

        Asian.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Asian.setForeground(new java.awt.Color(255, 255, 255));
        Asian.setText("Tiramisu");
        Asian.setOpaque(false);
        getContentPane().add(Asian);
        Asian.setBounds(120, 250, 110, 25);

        Coffee.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Coffee.setForeground(new java.awt.Color(255, 255, 255));
        Coffee.setText("Wild Mushroom");
        Coffee.setOpaque(false);
        getContentPane().add(Coffee);
        Coffee.setBounds(80, 180, 130, 25);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Casino/wine3Resized.jpg"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 440, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restaurant().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox American;
    private javax.swing.JCheckBox Asian;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel BreakfastLabel;
    private javax.swing.JCheckBox Burger;
    private javax.swing.JCheckBox Cereal;
    private javax.swing.JCheckBox Coffee;
    private javax.swing.JCheckBox Continental;
    private javax.swing.JLabel Dinner;
    private javax.swing.JLabel LunchLabel;
    private javax.swing.JCheckBox Pasta;
    private javax.swing.JCheckBox Salad;
    private javax.swing.JCheckBox Waffles;
    // End of variables declaration//GEN-END:variables
}
