/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Casino;

/**
 * The user can input a check-in date, a check-out date, type of room and press
 * the Check Availability button.  Once the button is activated, either the 
 * word Available or Not Available appears under the button.  
 * 
 * The Member name, Casino, and Member Level are prefilled from the Menu page.
 * 
 */
public class Rooms extends javax.swing.JFrame {

    /**
     * Creates new form Rooms
     */
    public Rooms() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CheckInDate = new javax.swing.JLabel();
        DateOfCheckIn = new javax.swing.JTextField();
        CheckOutDate = new javax.swing.JLabel();
        DateOfCheckOut = new javax.swing.JTextField();
        RoomTypeLabel = new javax.swing.JLabel();
        RoomList = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        CheckAvailability = new javax.swing.JButton();
        AvailableYesNo = new javax.swing.JLabel();
        MemberFirstNamePrefill1 = new javax.swing.JTextField();
        MemberLastNamePrefill1 = new javax.swing.JTextField();
        CasinoPrefill1 = new javax.swing.JTextField();
        MemberLevelPrefill = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Rooms"); // NOI18N
        setPreferredSize(new java.awt.Dimension(400, 330));
        setResizable(false);
        getContentPane().setLayout(null);

        CheckInDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CheckInDate.setForeground(new java.awt.Color(255, 255, 255));
        CheckInDate.setText("Check-In Date");
        getContentPane().add(CheckInDate);
        CheckInDate.setBounds(10, 150, 90, 20);

        DateOfCheckIn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DateOfCheckIn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        DateOfCheckIn.setOpaque(false);
        getContentPane().add(DateOfCheckIn);
        DateOfCheckIn.setBounds(110, 150, 110, 30);

        CheckOutDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CheckOutDate.setForeground(new java.awt.Color(255, 255, 255));
        CheckOutDate.setText("Check-Out Date");
        getContentPane().add(CheckOutDate);
        CheckOutDate.setBounds(3, 190, 97, 20);

        DateOfCheckOut.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DateOfCheckOut.setForeground(new java.awt.Color(255, 255, 255));
        DateOfCheckOut.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        DateOfCheckOut.setOpaque(false);
        getContentPane().add(DateOfCheckOut);
        DateOfCheckOut.setBounds(110, 190, 110, 30);

        RoomTypeLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RoomTypeLabel.setForeground(new java.awt.Color(255, 255, 255));
        RoomTypeLabel.setText("Type of Room");
        getContentPane().add(RoomTypeLabel);
        RoomTypeLabel.setBounds(10, 230, 90, 20);

        jList2.setBackground(new java.awt.Color(51, 0, 0));
        jList2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jList2.setForeground(new java.awt.Color(255, 255, 255));
        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "King", "Queen", "Double" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList2.setOpaque(false);
        RoomList.setViewportView(jList2);

        getContentPane().add(RoomList);
        RoomList.setBounds(110, 230, 110, 30);

        CheckAvailability.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CheckAvailability.setText("Check Availability");
        CheckAvailability.setOpaque(false);
        CheckAvailability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckAvailabilityActionPerformed(evt);
            }
        });
        getContentPane().add(CheckAvailability);
        CheckAvailability.setBounds(250, 150, 140, 23);

        AvailableYesNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AvailableYesNo.setForeground(new java.awt.Color(255, 255, 255));
        AvailableYesNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(AvailableYesNo);
        AvailableYesNo.setBounds(250, 180, 140, 20);

        MemberFirstNamePrefill1.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        MemberFirstNamePrefill1.setForeground(new java.awt.Color(255, 255, 255));
        MemberFirstNamePrefill1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        MemberFirstNamePrefill1.setText("First");
        MemberFirstNamePrefill1.setBorder(null);
        MemberFirstNamePrefill1.setOpaque(false);
        MemberFirstNamePrefill1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemberFirstNamePrefill1ActionPerformed(evt);
            }
        });
        getContentPane().add(MemberFirstNamePrefill1);
        MemberFirstNamePrefill1.setBounds(240, 250, 60, 20);

        MemberLastNamePrefill1.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        MemberLastNamePrefill1.setForeground(new java.awt.Color(255, 255, 255));
        MemberLastNamePrefill1.setText(" Last Prefill");
        MemberLastNamePrefill1.setBorder(null);
        MemberLastNamePrefill1.setOpaque(false);
        MemberLastNamePrefill1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemberLastNamePrefill1ActionPerformed(evt);
            }
        });
        getContentPane().add(MemberLastNamePrefill1);
        MemberLastNamePrefill1.setBounds(300, 250, 90, 20);

        CasinoPrefill1.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        CasinoPrefill1.setForeground(new java.awt.Color(255, 255, 255));
        CasinoPrefill1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CasinoPrefill1.setText("Casino Prefill");
        CasinoPrefill1.setBorder(null);
        CasinoPrefill1.setOpaque(false);
        CasinoPrefill1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CasinoPrefill1ActionPerformed(evt);
            }
        });
        getContentPane().add(CasinoPrefill1);
        CasinoPrefill1.setBounds(240, 260, 130, 20);

        MemberLevelPrefill.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        MemberLevelPrefill.setForeground(new java.awt.Color(255, 255, 255));
        MemberLevelPrefill.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MemberLevelPrefill.setText("Member Level Prefill");
        MemberLevelPrefill.setBorder(null);
        MemberLevelPrefill.setOpaque(false);
        MemberLevelPrefill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemberLevelPrefillActionPerformed(evt);
            }
        });
        getContentPane().add(MemberLevelPrefill);
        MemberLevelPrefill.setBounds(250, 270, 130, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Casino/hotel room resized.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CheckAvailabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckAvailabilityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckAvailabilityActionPerformed

    private void MemberFirstNamePrefill1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MemberFirstNamePrefill1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MemberFirstNamePrefill1ActionPerformed

    private void MemberLastNamePrefill1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MemberLastNamePrefill1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MemberLastNamePrefill1ActionPerformed

    private void CasinoPrefill1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CasinoPrefill1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CasinoPrefill1ActionPerformed

    private void MemberLevelPrefillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MemberLevelPrefillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MemberLevelPrefillActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rooms().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AvailableYesNo;
    private javax.swing.JTextField CasinoPrefill1;
    private javax.swing.JButton CheckAvailability;
    private javax.swing.JLabel CheckInDate;
    private javax.swing.JLabel CheckOutDate;
    private javax.swing.JTextField DateOfCheckIn;
    private javax.swing.JTextField DateOfCheckOut;
    private javax.swing.JTextField MemberFirstNamePrefill1;
    private javax.swing.JTextField MemberLastNamePrefill1;
    private javax.swing.JTextField MemberLevelPrefill;
    private javax.swing.JScrollPane RoomList;
    private javax.swing.JLabel RoomTypeLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList2;
    // End of variables declaration//GEN-END:variables
}
