/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Casino;

/**
 * The user can input a check-in date, a check-out date, type of room and press
 * the Check Availability button.  Once the button is activated, either the 
 * word Available or Not Available appears under the button.  
 * 
 * The Member name, Casino, and Member Level are prefilled from the Menu page.
 * 
 */
public class Rooms extends javax.swing.JFrame {

    /**
     * Creates new form Rooms
     */
    public Rooms() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CheckInDate = new javax.swing.JLabel();
        DateOfCheckIn = new javax.swing.JTextField();
        CheckOutDate = new javax.swing.JLabel();
        DateOfCheckOut = new javax.swing.JTextField();
        RoomTypeLabel = new javax.swing.JLabel();
        RoomList = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        CheckAvailability = new javax.swing.JButton();
        availableRooms = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Rooms"); // NOI18N
        setPreferredSize(new java.awt.Dimension(400, 330));
        setResizable(false);
        getContentPane().setLayout(null);

        CheckInDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CheckInDate.setForeground(new java.awt.Color(255, 255, 255));
        CheckInDate.setText("Check-In Date");
        getContentPane().add(CheckInDate);
        CheckInDate.setBounds(10, 150, 90, 20);

        DateOfCheckIn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DateOfCheckIn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        DateOfCheckIn.setOpaque(false);
        getContentPane().add(DateOfCheckIn);
        DateOfCheckIn.setBounds(110, 150, 110, 30);

        CheckOutDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CheckOutDate.setForeground(new java.awt.Color(255, 255, 255));
        CheckOutDate.setText("Check-Out Date");
        getContentPane().add(CheckOutDate);
        CheckOutDate.setBounds(3, 190, 97, 20);

        DateOfCheckOut.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DateOfCheckOut.setForeground(new java.awt.Color(255, 255, 255));
        DateOfCheckOut.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        DateOfCheckOut.setOpaque(false);
        getContentPane().add(DateOfCheckOut);
        DateOfCheckOut.setBounds(110, 190, 110, 30);

        RoomTypeLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RoomTypeLabel.setForeground(new java.awt.Color(255, 255, 255));
        RoomTypeLabel.setText("Type of Room");
        getContentPane().add(RoomTypeLabel);
        RoomTypeLabel.setBounds(10, 230, 90, 20);

        jList2.setBackground(new java.awt.Color(51, 0, 0));
        jList2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jList2.setForeground(new java.awt.Color(255, 255, 255));
        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Double", "Queen", "King Studio" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList2.setOpaque(false);
        RoomList.setViewportView(jList2);

        getContentPane().add(RoomList);
        RoomList.setBounds(110, 230, 110, 30);

        CheckAvailability.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CheckAvailability.setText("Check Availability");
        CheckAvailability.setOpaque(false);
        CheckAvailability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckAvailabilityActionPerformed(evt);
            }
        });
        getContentPane().add(CheckAvailability);
        CheckAvailability.setBounds(250, 150, 140, 23);

        availableRooms.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jList1.setBackground(new java.awt.Color(51, 0, 0));
        jList1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jList1.setForeground(new java.awt.Color(255, 255, 255));
        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        availableRooms.setViewportView(jList1);

        getContentPane().add(availableRooms);
        availableRooms.setBounds(250, 180, 140, 60);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Casino/hotel room resized.jpg"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 400, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CheckAvailabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckAvailabilityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckAvailabilityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rooms().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton CheckAvailability;
    private javax.swing.JLabel CheckInDate;
    private javax.swing.JLabel CheckOutDate;
    private javax.swing.JTextField DateOfCheckIn;
    private javax.swing.JTextField DateOfCheckOut;
    private javax.swing.JScrollPane RoomList;
    private javax.swing.JLabel RoomTypeLabel;
    private javax.swing.JScrollPane availableRooms;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    // End of variables declaration//GEN-END:variables
}
