/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Casino;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JFrame;

/**
 *The user can schedule date and time the Member would like to go to the spa.  
 * Several treatments can be selected simultaneously.
 * 
 * The Member name, Casino, and Member Level are prefilled from the Menu page.
 */
public class Spa extends javax.swing.JFrame {

    /**
     */
    public Spa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DateOfService = new javax.swing.JLabel();
        DateField = new javax.swing.JTextField();
        TimeOfService = new javax.swing.JLabel();
        TimeField = new javax.swing.JTextField();
        TreatmentLabel = new javax.swing.JLabel();
        Facial = new javax.swing.JCheckBox();
        Haircut = new javax.swing.JCheckBox();
        Massage = new javax.swing.JCheckBox();
        Pedicure = new javax.swing.JCheckBox();
        ScheduleSession = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Spa"); // NOI18N
        setPreferredSize(new java.awt.Dimension(400, 250));
        setResizable(false);
        getContentPane().setLayout(null);

        DateOfService.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DateOfService.setText("Date Of Service");
        getContentPane().add(DateOfService);
        DateOfService.setBounds(120, 10, 100, 20);

        DateField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DateField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        DateField.setOpaque(false);
        DateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateFieldActionPerformed(evt);
            }
        });
        getContentPane().add(DateField);
        DateField.setBounds(220, 10, 80, 20);

        TimeOfService.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TimeOfService.setText("Time Of Service");
        getContentPane().add(TimeOfService);
        TimeOfService.setBounds(120, 40, 100, 20);

        TimeField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TimeField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TimeField.setOpaque(false);
        getContentPane().add(TimeField);
        TimeField.setBounds(220, 40, 80, 20);

        TreatmentLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TreatmentLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TreatmentLabel.setText("Treatment");
        getContentPane().add(TreatmentLabel);
        TreatmentLabel.setBounds(20, 50, 70, 20);

        Facial.setBackground(new java.awt.Color(0, 153, 0));
        Facial.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Facial.setText("Facial");
        Facial.setOpaque(false);
        getContentPane().add(Facial);
        Facial.setBounds(50, 70, 90, 25);

        Haircut.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Haircut.setText("Haircut");
        Haircut.setOpaque(false);
        getContentPane().add(Haircut);
        Haircut.setBounds(70, 90, 100, 25);

        Massage.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Massage.setText("Massage");
        Massage.setOpaque(false);
        getContentPane().add(Massage);
        Massage.setBounds(90, 110, 110, 25);

        Pedicure.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Pedicure.setText("Pedicure");
        Pedicure.setOpaque(false);
        getContentPane().add(Pedicure);
        Pedicure.setBounds(110, 130, 110, 25);

        ScheduleSession.setBackground(new java.awt.Color(0, 0, 0));
        ScheduleSession.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ScheduleSession.setForeground(new java.awt.Color(0, 0, 0));
        ScheduleSession.setText("Schedule Session");
        ScheduleSession.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ScheduleSession.setOpaque(false);
        getContentPane().add(ScheduleSession);
        ScheduleSession.setBounds(40, 190, 150, 30);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Casino/spa4resized.jpg"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 400, 230);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateFieldActionPerformed
   {
      setBackground (Color.cyan);
      setPreferredSize (new Dimension(500,500));
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Spa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Spa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Spa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Spa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Spa().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JTextField DateField;
    private javax.swing.JLabel DateOfService;
    private javax.swing.JCheckBox Facial;
    private javax.swing.JCheckBox Haircut;
    private javax.swing.JCheckBox Massage;
    private javax.swing.JCheckBox Pedicure;
    private javax.swing.JButton ScheduleSession;
    private javax.swing.JTextField TimeField;
    private javax.swing.JLabel TimeOfService;
    private javax.swing.JLabel TreatmentLabel;
    // End of variables declaration//GEN-END:variables
}
